name: deploy-ecs-docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  #构建docker镜像并推送到github包仓库
  build-and-push-image:
    runs-on: ubuntu-latest
    #权限
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_GITHUB }}

    - name: generate the image name
      id: generate-name-1
      run: echo "IMAGE1=${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }}-$(date +%s)" >> "$GITHUB_OUTPUT"
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: ${{ steps.generate-name-1.outputs.IMAGE1 }}

    - name: generate the second image name
      id: generate-name-2
      run: echo "IMAGE2=${{ env.REGISTRY }}/${{ env.REPO_NAME }}-nginx:${{ github.sha }}-$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Build and push second Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: ./nginx_conf/Dockerfile
        tags: ${{ steps.generate-name-2.outputs.IMAGE2 }}

    - name: ssh-to-ECS
      uses: appleboy/ssh-action@v1.0.3
      env:
        IMAGE1: ${{ steps.generate-name-1.outputs.IMAGE1 }}
        IMAGE2: ${{ steps.generate-name-2.outputs.IMAGE2 }}
      with:
        command_timeout: 5m
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: IMAGE1,IMAGE2
        script: | # 运行多行命令
            echo ${IMAGE1}
            echo ${IMAGE2}

            echo "[deploy] start deployment..."
            if [ ! -d "app" ]; then
              mkdir "app"
            fi
            # 进到当前文件夹
            cd app

            # 停止服务
            docker container stop `docker ps -aq`
            docker rm -f $(docker ps -aq)
            docker rmi -f $(docker images -q)
            pkill python3

            echo $CR_PAT | docker login ghcr.io -u emptydream-zdb --password-stdin
            docker pull ${IMAGE1}
            docker pull ${IMAGE2}

            docker run --network=host -d ${IMAGE1} python3 ./server_north_controll/server.py
            docker run --network=host -d ${IMAGE1} python3 ./server_user_manager/server.py
            docker run --network=host -d ${IMAGE1} python3 ./server_realtime_data/server.py
            docker run --network=host -d ${IMAGE1} python3 ./server_event_manager/server.py
            docker run --network=host -d ${IMAGE1} python3 ./server_elecdata_manager/server.py
            docker run --network=host -d ${IMAGE1} python3 ./server_south_device/server.py
            docker run --network=host -d ${IMAGE2}